# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plotter.ui'
#
# Created by: PySide6 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets
from PySide6.QtWidgets import *
from PySide6.QtCore import *
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
import matplotlib.pyplot as plt
from calculations import Calculations


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(700, 700)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(170, 120, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setEnabled(False)
        self.equation_input = QtWidgets.QLineEdit(Form)
        self.equation_input.setGeometry(QtCore.QRect(20, 40, 121, 22))
        self.equation_input.setObjectName("equation_input")
        self.min_val_input = QtWidgets.QLineEdit(Form)
        self.min_val_input.setGeometry(QtCore.QRect(20, 120, 51, 22))
        self.min_val_input.setObjectName("min_val_input")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 61, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 100, 61, 16))
        self.label_3.setObjectName("label_3")
        self.max_val_input = QtWidgets.QLineEdit(Form)
        self.max_val_input.setGeometry(QtCore.QRect(90, 120, 51, 22))
        self.max_val_input.setObjectName("max_val_input")
        self.eq_err_lbl = QtWidgets.QLabel(Form)
        self.eq_err_lbl.setGeometry(QtCore.QRect(20, 70, 261, 20))
        self.eq_err_lbl.setObjectName("eq_err_lbl")

        self.bond_err_lbl = QtWidgets.QLabel(Form)
        self.bond_err_lbl.setGeometry(QtCore.QRect(20, 150, 411, 16))
        self.bond_err_lbl.setObjectName("bond_err_lbl")

        self.figure = plt.figure()
        self.canvas = FigureCanvas(self.figure)
        self.toolbar = NavigationToolbar(self.canvas, Form)
        self.equation_input.textEdited.connect(self.is_eq_valid)
        self.min_val_input.textEdited.connect(self.is_min_valid)
        self.max_val_input.textEdited.connect(self.is_max_valid)
        self.pushButton.clicked.connect(self.plot)

        self.verticalLayoutWidget = QWidget(Form)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 200, 551, 500))
        self.layout = QVBoxLayout(self.verticalLayoutWidget)
        self.layout.setObjectName(u"verticalLayout_4")
        self.layout.setContentsMargins(0, 0, 0, 0)
        self.layout.addWidget(self.toolbar)
        self.layout.addWidget(self.canvas)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Plot"))
        self.label.setText(_translate("Form", "Equation of x"))
        self.label_2.setText(_translate("Form", "Min value"))
        self.label_3.setText(_translate("Form", "Max value"))
        self.eq_err_lbl.setText(_translate("Form", ""))
        self.bond_err_lbl.setText(_translate("Form", ""))


    def plot(self):
        #plot function that show plot of f(x) on canvas
        self.figure.clear()
        # create an axis
        ax = self.figure.add_subplot(111)
        x, y = self.evaluation()
        # plot data
        ax.plot(x, y)
        plt.xlabel('x')
        plt.ylabel('f(x)')
        plt.grid()
        # refresh canvas
        self.canvas.draw()

    def evaluation(self):
        #this function reads inputs from the ui and return x list and y list that will be plotted
        min = float(self.min_val_input.text())
        max = float(self.max_val_input.text())
        equation = self.equation_input.text()
        calc = Calculations()
        x_val, y_val =  calc.evaluation(equation, min, max)
        return x_val, y_val

    def is_eq_valid(self):
        #text input validation for equation value text box
        eq = self.equation_input.text()
        if '^' in eq: eq = eq.replace('^', '**')

        try:
            x = 5.12
            y = eval(eq)
            self.eq_err_lbl.setText('')
            self.pushButton.setEnabled(True)
        except:
            self.eq_err_lbl.setText('Invalid input, please inter a right equation of x')
            self.eq_err_lbl.setStyleSheet("QLabel { color : red; }")
            self.pushButton.setEnabled(False)
        if self.min_val_input.text() == '' or self.max_val_input.text() == '':
            self.pushButton.setEnabled(False)


    def is_max_valid(self):
        # text input validation for max value text box

        try:
            minx = float(self.min_val_input.text())
            maxx = float(self.max_val_input.text())
            self.pushButton.setEnabled(True)
            self.bond_err_lbl.setText('')
            if minx > maxx:
                self.pushButton.setEnabled(False)
                self.bond_err_lbl.setText('max value must be greater than min value')
                self.bond_err_lbl.setStyleSheet("QLabel { color : red; }")
        except:
            self.bond_err_lbl.setText('Invalid input, please inter suitable number in each field')
            self.bond_err_lbl.setStyleSheet("QLabel { color : red; }")
            self.pushButton.setEnabled(False)
        if self.equation_input.text() == '' or self.min_val_input.text() == '':
            self.pushButton.setEnabled(False)


    def is_min_valid(self):
        # text input validation for min value text box

        try:
            minx = float(self.min_val_input.text())
            self.pushButton.setEnabled(True)
            self.bond_err_lbl.setText('')
            if self.max_val_input.text() != '' and minx > float(self.max_val_input.text()):
                self.pushButton.setEnabled(False)
                self.bond_err_lbl.setText('max value must be greater than min value')
                self.bond_err_lbl.setStyleSheet("QLabel { color : red; }")
        except:
            self.bond_err_lbl.setText('Invalid input, please inter suitable number in each field')
            self.bond_err_lbl.setStyleSheet("QLabel { color : red; }")
            self.pushButton.setEnabled(False)
        if self.equation_input.text() == '' or self.max_val_input.text() == '' :
            self.pushButton.setEnabled(False)







if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
